<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Felix Kurth
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\EbookReader\Controller;

use OCA\EbookReader\Http\AbstractOCSController;
use OCA\EbookReader\Service\AnnotationService;
use OCA\EbookReader\Service\LibraryService;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\Attribute\ApiRoute;
use OCP\AppFramework\Http\Attribute\NoAdminRequired;
use OCP\AppFramework\Http\Attribute\UserRateLimit;
use OCP\AppFramework\Http\DataResponse;
use OCP\AppFramework\OCS\OCSBadRequestException;
use OCP\AppFramework\OCS\OCSForbiddenException;
use OCP\AppFramework\OCS\OCSNotFoundException;
use OCP\Files\NotFoundException;
use OCP\IRequest;

/**
 * Highlights, notes and bookmarks. The user always comes from the session, never from the request.
 *
 * @psalm-import-type EbookReaderAnnotation from \OCA\EbookReader\ResponseDefinitions
 * @psalm-import-type EbookReaderLocator from \OCA\EbookReader\ResponseDefinitions
 */
class AnnotationsController extends AbstractOCSController {
	public function __construct(
		IRequest $request,
		?string $userId,
		private AnnotationService $annotations,
		private LibraryService $library,
	) {
		parent::__construct($request, $userId);
	}

	/**
	 * List the highlights, notes and bookmarks of a book
	 *
	 * @param int $fileId Nextcloud file id
	 * @return DataResponse<Http::STATUS_OK, array{annotations: list<EbookReaderAnnotation>}, array{}>
	 * @throws OCSNotFoundException Book file not accessible
	 * @throws OCSForbiddenException Not logged in or the content of the book is not readable (view-only share)
	 *
	 * 200: Annotations returned (without deleted ones)
	 */
	#[NoAdminRequired]
	#[ApiRoute(verb: 'GET', url: '/api/v1/books/{fileId}/annotations', requirements: ['fileId' => '\d+'])]
	public function index(int $fileId): DataResponse {
		$userId = $this->uid();
		$this->assertReadable($userId, $fileId);
		return new DataResponse(['annotations' => array_map(
			static fn ($a): array => $a->toApi(),
			$this->annotations->list($userId, $fileId),
		)]);
	}

	/**
	 * Create an annotation, or update the one with the same uuid (last write wins on clientUpdatedAt)
	 *
	 * @param int $fileId Nextcloud file id
	 * @param 'highlight'|'note'|'bookmark' $type Kind of annotation
	 * @param EbookReaderLocator $locator Readium-like locator (same shape as the reading progress)
	 * @param string|null $uuid Client generated UUID, generated by the server when missing
	 * @param string|null $text Selected text excerpt (max 2000 characters)
	 * @param string|null $note Note (max 10000 characters)
	 * @param 'yellow'|'green'|'blue'|'pink'|'purple'|null $color Highlight color
	 * @param int|null $clientUpdatedAt Client timestamp in milliseconds (default: now)
	 * @param int|null $createdAt Creation time in milliseconds when the annotation was made offline
	 * @return DataResponse<Http::STATUS_OK, EbookReaderAnnotation, array{}>|DataResponse<Http::STATUS_CONFLICT, array{current: EbookReaderAnnotation}, array{}>
	 * @throws OCSBadRequestException Invalid input
	 * @throws OCSNotFoundException Book file not accessible
	 * @throws OCSForbiddenException Not logged in or the content of the book is not readable (view-only share)
	 *
	 * 200: Annotation stored
	 * 409: The server has a newer version, it is returned as current
	 */
	#[NoAdminRequired]
	#[UserRateLimit(limit: 240, period: 60)]
	#[ApiRoute(verb: 'POST', url: '/api/v1/books/{fileId}/annotations', requirements: ['fileId' => '\d+'])]
	public function create(int $fileId, string $type, array $locator, ?string $uuid = null, ?string $text = null, ?string $note = null, ?string $color = null, ?int $clientUpdatedAt = null, ?int $createdAt = null): DataResponse {
		$userId = $this->uid();
		$this->assertReadable($userId, $fileId);
		try {
			$result = $this->annotations->upsert($userId, $fileId, $uuid, $type, $locator, $text, $note, $color, $clientUpdatedAt, $createdAt);
		} catch (\InvalidArgumentException $e) {
			throw new OCSBadRequestException($e->getMessage());
		}
		if ($result['status'] === 'conflict') {
			return new DataResponse(['current' => $result['annotation']->toApi()], Http::STATUS_CONFLICT);
		}
		return new DataResponse($result['annotation']->toApi());
	}

	/**
	 * Change an annotation (only the given fields; an empty note or color clears it)
	 *
	 * @param string $uuid Annotation UUID
	 * @param EbookReaderLocator|null $locator New locator
	 * @param string|null $text New text excerpt
	 * @param string|null $note New note, empty string removes it
	 * @param 'yellow'|'green'|'blue'|'pink'|'purple'|''|null $color New color, empty string removes it
	 * @param int|null $clientUpdatedAt Client timestamp in milliseconds (default: now)
	 * @return DataResponse<Http::STATUS_OK, EbookReaderAnnotation, array{}>|DataResponse<Http::STATUS_CONFLICT, array{current: EbookReaderAnnotation}, array{}>
	 * @throws OCSBadRequestException Invalid input
	 * @throws OCSNotFoundException Annotation not found
	 * @throws OCSForbiddenException Not logged in
	 *
	 * 200: Annotation updated
	 * 409: The server has a newer version, it is returned as current
	 */
	#[NoAdminRequired]
	#[UserRateLimit(limit: 240, period: 60)]
	#[ApiRoute(verb: 'PATCH', url: '/api/v1/annotations/{uuid}', requirements: ['uuid' => '[0-9A-Fa-f-]{36}'])]
	public function update(string $uuid, ?array $locator = null, ?string $text = null, ?string $note = null, ?string $color = null, ?int $clientUpdatedAt = null): DataResponse {
		$userId = $this->uid();
		try {
			$result = $this->annotations->patch($userId, $uuid, $locator, $text, $note, $color, $clientUpdatedAt);
		} catch (\InvalidArgumentException $e) {
			throw new OCSBadRequestException($e->getMessage());
		}
		if ($result === null) {
			throw new OCSNotFoundException('Annotation not found');
		}
		if ($result['status'] === 'conflict') {
			return new DataResponse(['current' => $result['annotation']->toApi()], Http::STATUS_CONFLICT);
		}
		return new DataResponse($result['annotation']->toApi());
	}

	/**
	 * Delete an annotation (the row stays as a tombstone so that other clients can sync the deletion)
	 *
	 * @param string $uuid Annotation UUID
	 * @param int|null $clientUpdatedAt Client timestamp in milliseconds (default: now)
	 * @return DataResponse<Http::STATUS_OK, EbookReaderAnnotation, array{}>|DataResponse<Http::STATUS_CONFLICT, array{current: EbookReaderAnnotation}, array{}>
	 * @throws OCSNotFoundException Annotation not found
	 * @throws OCSForbiddenException Not logged in
	 *
	 * 200: Annotation deleted (also when it already was), the tombstone is returned
	 * 409: The annotation was edited more recently than the client timestamp
	 */
	#[NoAdminRequired]
	#[UserRateLimit(limit: 240, period: 60)]
	#[ApiRoute(verb: 'DELETE', url: '/api/v1/annotations/{uuid}', requirements: ['uuid' => '[0-9A-Fa-f-]{36}'])]
	public function destroy(string $uuid, ?int $clientUpdatedAt = null): DataResponse {
		$userId = $this->uid();
		try {
			$result = $this->annotations->delete($userId, $uuid, $clientUpdatedAt);
		} catch (\InvalidArgumentException $e) {
			throw new OCSBadRequestException($e->getMessage());
		}
		if ($result === null) {
			throw new OCSNotFoundException('Annotation not found');
		}
		if ($result['status'] === 'conflict') {
			return new DataResponse(['current' => $result['annotation']->toApi()], Http::STATUS_CONFLICT);
		}
		return new DataResponse($result['annotation']->toApi());
	}

	/**
	 * The user must see the file, and the content must be readable: highlights carry excerpts of the book text, which
	 * must not leak through a download-disabled share.
	 *
	 * @throws OCSNotFoundException
	 * @throws OCSForbiddenException
	 */
	private function assertReadable(string $userId, int $fileId): void {
		try {
			$file = $this->library->getFileForUser($userId, $fileId);
		} catch (NotFoundException) {
			throw new OCSNotFoundException('File not found');
		}
		if (!$this->library->canReadContent($file)) {
			throw new OCSForbiddenException('The content of this book is not readable');
		}
	}
}
