#!/usr/bin/env node
/**
 * SPDX-FileCopyrightText: 2026 Felix Kurth
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
/**
 * Translation tooling (the app is not in Nextcloud's Transifex pipeline).
 *
 *   node scripts/l10n.mjs extract [--prune]   scan sources, write translationfiles/source.json,
 *                                             regenerate l10n/<lang>.js from l10n/<lang>.json
 *                                             (--prune also drops stale keys from the json files)
 *   node scripts/l10n.mjs check [--strict]    validate without writing (CI)
 *   node scripts/l10n.mjs missing <lang>      print the missing keys of a language as JSON
 *                                             (English text as value) to paste into l10n/<lang>.json
 *
 * Errors (exit code 1): malformed json, wrong pluralForm, plural arrays of the wrong length,
 * placeholders ({name}, %s, %1$s, %d, %n) that differ from the English source, l10n/<lang>.js out of
 * sync with l10n/<lang>.json. Warnings (exit code 0, 1 with --strict): missing and stale keys,
 * outdated translationfiles/source.json, calls with non-literal text.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
	buildCatalogue,
	checkLanguage,
	extractInfoXml,
	extractJs,
	extractPhp,
	PLURAL_FORMS,
	renderJs,
	renderJson,
	sortTranslations,
	splitPluralKey,
} from './l10n-lib.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const L10N_DIR = join(ROOT, 'l10n')
const CATALOGUE = join(ROOT, 'translationfiles', 'source.json')

/**
 * @param {string} dir
 * @param {(path: string) => boolean} accept
 * @return {string[]}
 */
function walk(dir, accept) {
	const out = []
	for (const e of readdirSync(dir, { withFileTypes: true })) {
		const p = join(dir, e.name)
		if (e.isDirectory()) {
			if (e.name !== 'node_modules' && e.name !== 'vendor') {
				out.push(...walk(p, accept))
			}
		} else if (accept(p)) {
			out.push(p)
		}
	}
	return out.sort()
}

const rel = (p) => relative(ROOT, p).split(sep).join('/')

/**
 * @return {{ catalogue: import('./l10n-lib.mjs').CatalogueEntry[], warnings: { file: string, line: number, message: string }[] }}
 */
function scan() {
	const strings = []
	const warnings = []
	const add = (r) => {
		strings.push(...r.strings)
		warnings.push(...r.warnings)
	}
	const isJs = (p) => /\.(vue|ts)$/.test(p) && !/\.(test|spec)\.ts$/.test(p) && !p.endsWith('.d.ts')
	for (const f of walk(join(ROOT, 'src'), isJs)) {
		add(extractJs(readFileSync(f, 'utf8'), rel(f)))
	}
	for (const f of walk(join(ROOT, 'lib'), (p) => p.endsWith('.php'))) {
		add(extractPhp(readFileSync(f, 'utf8'), rel(f)))
	}
	const info = join(ROOT, 'appinfo', 'info.xml')
	add(extractInfoXml(readFileSync(info, 'utf8'), rel(info)))
	return { catalogue: buildCatalogue(strings), warnings }
}

/**
 * @return {string[]}
 */
function languages() {
	if (!existsSync(L10N_DIR)) {
		return []
	}
	return readdirSync(L10N_DIR).filter((f) => f.endsWith('.json')).map((f) => f.slice(0, -5)).sort()
}

/**
 * @param {string} lang
 * @return {{ data: unknown, error?: string }}
 */
function readLang(lang) {
	try {
		return { data: JSON.parse(readFileSync(join(L10N_DIR, `${lang}.json`), 'utf8')) }
	} catch (e) {
		return { data: null, error: `l10n/${lang}.json: invalid JSON (${e instanceof Error ? e.message : e})` }
	}
}

const catalogueJson = (catalogue) => JSON.stringify({
	_comment: 'Generated by `npm run l10n:extract` from src/, lib/ and appinfo/info.xml. Do not edit.',
	strings: catalogue,
}, null, '\t') + '\n'

const [cmd = 'check', ...args] = process.argv.slice(2)
const strict = args.includes('--strict')
const prune = args.includes('--prune')

if (cmd === 'missing') {
	const lang = args.find((a) => !a.startsWith('--'))
	if (!lang) {
		console.error('usage: node scripts/l10n.mjs missing <lang>')
		process.exit(2)
	}
	const { catalogue } = scan()
	const { data } = existsSync(join(L10N_DIR, `${lang}.json`)) ? readLang(lang) : { data: { translations: {} } }
	const tr = data?.translations ?? {}
	const nplurals = Number(/nplurals=(\d+)/.exec(data?.pluralForm ?? PLURAL_FORMS[lang] ?? '')?.[1] ?? 2)
	const out = {}
	for (const e of catalogue) {
		const v = tr[e.id]
		if (v === undefined || v === '' || (Array.isArray(v) && v.some((x) => x === ''))) {
			out[e.id] = e.plural === undefined ? e.id : Array.from({ length: nplurals }, (_, i) => (i === 0 && nplurals > 1 ? e.singular : e.plural))
		}
	}
	process.stdout.write(JSON.stringify(out, null, '\t') + '\n')
	process.exit(0)
}

if (cmd !== 'extract' && cmd !== 'check') {
	console.error('usage: node scripts/l10n.mjs extract [--prune] | check [--strict] | missing <lang>')
	process.exit(2)
}

const { catalogue, warnings: scanWarnings } = scan()
const plural = catalogue.filter((e) => e.plural !== undefined).length
const errors = []
const warnings = scanWarnings.map((w) => `${w.file}:${w.line}: ${w.message}`)

const expectedCatalogue = catalogueJson(catalogue)
if (cmd === 'extract') {
	writeFileSync(CATALOGUE, expectedCatalogue)
	console.log(`translationfiles/source.json: ${catalogue.length} strings (${plural} plural)`)
} else if (!existsSync(CATALOGUE) || readFileSync(CATALOGUE, 'utf8').replace(/\r\n/g, '\n') !== expectedCatalogue) {
	warnings.push('translationfiles/source.json is outdated, run `npm run l10n:extract`')
}

const summary = []
const missingByLang = {}
for (const lang of languages()) {
	const { data, error } = readLang(lang)
	if (error) {
		errors.push(error)
		continue
	}
	const report = checkLanguage(lang, data, catalogue)
	errors.push(...report.errors.map((e) => `l10n/${lang}.json: ${e}`))
	missingByLang[lang] = report.missing
	if (report.stale.length > 0) {
		if (cmd === 'extract' && prune) {
			for (const k of report.stale) {
				delete data.translations[k]
			}
			console.log(`l10n/${lang}.json: removed ${report.stale.length} stale keys`)
		} else {
			warnings.push(`l10n/${lang}.json: ${report.stale.length} stale keys (not in the source any more; \`npm run l10n:extract -- --prune\` removes them):\n${report.stale.map((k) => `    ${JSON.stringify(k)}`).join('\n')}`)
		}
	}
	summary.push(`${lang}: ${catalogue.length - report.missing.length}/${catalogue.length} translated`)

	const translations = data && typeof data === 'object' && data.translations && typeof data.translations === 'object' ? data.translations : null
	if (translations && typeof data.pluralForm === 'string') {
		const sorted = sortTranslations(translations)
		const js = renderJs(sorted, data.pluralForm)
		const jsPath = join(L10N_DIR, `${lang}.js`)
		if (cmd === 'extract') {
			writeFileSync(join(L10N_DIR, `${lang}.json`), renderJson(sorted, data.pluralForm))
			writeFileSync(jsPath, js)
		} else if (!existsSync(jsPath) || readFileSync(jsPath, 'utf8').replace(/\r\n/g, '\n') !== js) {
			errors.push(`l10n/${lang}.js is out of sync with l10n/${lang}.json, run \`npm run l10n:extract\``)
		}
	}
}

for (const [lang, keys] of Object.entries(missingByLang)) {
	if (keys.length > 0) {
		warnings.push(`l10n/${lang}.json: ${keys.length} missing (\`npm run l10n:missing ${lang}\` prints them as JSON):\n${keys.map((k) => {
			const p = splitPluralKey(k)
			return `    ${JSON.stringify(k)}${p ? ' (plural)' : ''}`
		}).join('\n')}`)
	}
}

for (const w of warnings) {
	console.warn(`warning: ${w}`)
}
for (const e of errors) {
	console.error(`error: ${e}`)
}
console.log(`${catalogue.length} source strings (${plural} plural). ${summary.join(', ') || 'no languages in l10n/'}`)
console.log(`${errors.length} errors, ${warnings.length} warnings`)
process.exit(errors.length > 0 || (strict && warnings.length > 0) ? 1 : 0)
