// Ambient declarations for the vendored (untyped) foliate-js modules.
declare module '*/foliate-js/view.js'
declare module '*/foliate-js/epub.js'
declare module '*/foliate-js/comic-book.js'
declare module '*/foliate-js/fb2.js'
declare module '*/foliate-js/mobi.js'
declare module '*/foliate-js/search.js'
declare module '*/foliate-js/vendor/zip.js'
declare module '*/foliate-js/vendor/fflate.js'
declare module '*/foliate-js/epubcfi.js'
declare module '*/foliate-js/overlayer.js'
